CREATE TABLE logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts BIGINT NOT NULL,
    ts_nanos BIGINT NOT NULL,
    level TEXT NOT NULL,
    target TEXT NOT NULL,
    feedback_log_body TEXT,
    module_path TEXT,
    file TEXT,
    line BIGINT,
    thread_id TEXT,
    process_uuid TEXT,
    estimated_bytes BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_logs_ts ON logs(ts DESC, ts_nanos DESC, id DESC);
CREATE INDEX idx_logs_thread_id ON logs(thread_id);
CREATE INDEX idx_logs_thread_id_ts ON logs(thread_id, ts DESC, ts_nanos DESC, id DESC);
CREATE INDEX idx_logs_process_uuid_threadless_ts
    ON logs(process_uuid, ts DESC, ts_nanos DESC, id DESC)
    WHERE thread_id IS NULL;
